apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: blt
  namespace: blt
  labels:
    kubevirt.io/os: linux
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
          - name: vlan10
            bridge: {}
          - name: vlan20
            bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 4096M
      networks:
      - name: default
        pod: {}
      - name: vlan10
        multus:
          networkName: kube-public/vlan10-bridge
      - name: vlan20
        multus:
          networkName: kube-public/vlan20-bridge
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: blt-pvc
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: blt
            ssh_pwauth: true
            disable_root: false
            chpasswd:
              list: |
                root:password
                debian:password
              expire: False
            packages:
              - ifupdown
              - openjdk-21-jre
              - curl
              - ca-certificates
                    
            write_files:
              - path: /etc/network/interfaces
                content: |
                  auto lo
                  iface lo inet loopback

                  auto enp1s0
                  iface enp1s0 inet dhcp

                  auto enp2s0
                  iface enp2s0 inet dhcp

                  auto enp3s0
                  iface enp3s0 inet dhcp
        
          runcmd:
            - ifdown -a || true
            - ifup -a
            curl -LO https://github.com/Deep-Symmetry/beat-link-trigger/releases/download/latest-preview/beat-link-trigger-8.1.0-Preview.jar
            # - java -jar beat-link-trigger-8.1.0-Preview.jar
        name: cloudinitdisk
