apiVersion: v1
kind: Service
metadata:
  name: blt-xz-service
  namespace: blt-xz
  annotations:
    external-dns.alpha.kubernetes.io/hostname: blt-xz.svc.technotut.net
spec:
  selector:
    vm.kubevirt.io/name: blt-xz
  type: LoadBalancer
  loadBalancerIP: 10.11.210.253
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: vnc
      port: 5901
      targetPort: 5901
